### PR TITLE
Trap types

### PR DESCRIPTION
**Pull request by felimomo**

### CODE REVIEW

**Comment by cboettig** [comment]
@felimomo tests are failing, can you add ray to the https://github.com/boettiger-lab/rl4greencrab/blob/main/pyproject.toml#L21

**Comment by cboettig** [comment]
@felimomo Did we ever resolve what the difference was between the built-in `evaluate` method in stable baselines and our custom one in ray?

**Review by cboettig — CHANGES_REQUESTED** [review]
Looks really great, thanks!  

See comments above about tests and the evaluate method

**Comment by felimomo** [comment]
Amazing! I'll add the ray dependency.

> @felimomo Did we ever resolve what the difference was between the built-in `evaluate` method in stable baselines and our custom one in ray?

Not in much detail - the main practical difference is time since `evaluate_policy` doesn't support parallelization (this gets especially limiting in environments with high stochasticity where we need high N statistics).

**Review by cboettig — APPROVED** [review]

**Pull request merged**
